include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    unused_import: warning
    dead_code: warning
    avoid_print: warning

  exclude:
    - legacy_src/**

linter:
  rules:
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    require_trailing_commas: true
